tasks:
  - init: install dependencies
    command: yarn
  - init: migrate database
    command: yarn db:reset:develop
  - init: start services
    command: yarn develop
ports:
  - port: 8080
    onOpen: open-browser