tasks:
  - before: docker-compose up -d; bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn db:migrate
    init: yarn set version 3.1.1 && yarn
    command: yarn develop
ports:
  - port: 8080
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
