tasks:
  - init: yarn set version 3.1.1 && yarn
    command: docker-compose up -d
ports:
  - port: 8080
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
