tasks:
  - before: docker-compose up -d
    init: yarn set version 3.1.1 && yarn
    command: yarn db:migrate; yarn develop
ports:
  - port: 8080
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
