language: node_js
node_js:
  - 8.10
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'DROP DATABASE IF EXISTS w8mngr-test;'
  - psql -c 'CREATE DATABASE w8mngr-test;'
  - psql w8mngr-test -c 'CREATE EXTENSION IF NOT EXISTS hstore'
  - psql w8mngr-test < ./test/initial_structure.sql
script:
  - npm run test:all
