language: node_js
node_js:
  - 8.10
services:
  - postgresql
before_script:
  - psql -c 'create database w8mngr_test;' -U postgres
  - psql -U postgres -a -f ./test/initial_structure.sql w8mngr_test
script:
  - npm run test:all
