language: node_js
node_js:
  - 8.10
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'DROP DATABASE IF EXISTS w8mngr_test;'
  - psql -c "create extension hstore"
  - psql -c 'create database w8mngr_test;'
  - psql -a -f ./test/initial_structure.sql w8mngr_test
script:
  - npm run test:all
