version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./test:/db-tools
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  api:
    build:
      context: .
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    depends_on:
      - db
    command: npm run start:lambda
    ports:
      - 9000:9000
  test:
    build:
      context: .
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    depends_on:
      - db
    command: npm run test:server
  web:
    build:
      context: .
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    depends_on:
      - api
    command: npm run start:client
    ports:
      - 8080:8080
volumes:
  database_data:
  node_modules:
