name = "w8mngr-graphql"
main = "api/graphql.ts"
compatibility_date = "2023-06-22"
node_compat = true

[[ d1_databases ]]
binding = "W8MNGR_1"
database_name = "w8mngr_1"
database_id = "e3ef7a16-f7f3-4b60-85bd-ac364bf676c9"
preview_database_id = "e3ef7a16-f7f3-4b60-85bd-ac364bf676c9"
